CREATE DATABASE EJEMPLO3;

USE EJEMPLO3;

CREATE TABLE CLIENTE
(
  NIF          CHAR(9),
  NOMBRE       VARCHAR(50),
  DIRECCION    VARCHAR(50),
  TELEFONO     CHAR(12),
  PRIMARY KEY (NIF)
);

DESCRIBE CLIENTE;


CREATE TABLE MONTADOR
(
  NIF          CHAR(9),
  NOMBRE       VARCHAR(50),
  DIRECCION    VARCHAR(50),
  TELEFONO     CHAR(9),
  PRIMARY KEY (NIF)
);

DESCRIBE MONTADOR;


CREATE TABLE MODELODORMITORIO
(
  COD          CHAR(3),
  PRIMARY KEY (COD)
);

DESCRIBE MODELODORMITORIO;


CREATE TABLE COMPRA
(
  NIF_C        CHAR(9),
  MODELO       CHAR(3),
  FECHACOMPRA  DATE,
  PRIMARY KEY (NIF_C, MODELO, FECHACOMPRA),
  FOREIGN KEY (NIF_C) REFERENCES CLIENTE(NIF),
  FOREIGN KEY (MODELO) REFERENCES MODELODORMITORIO(COD)
  
);

DESCRIBE COMPRA;

CREATE TABLE MONTA
(
  NIF_M        CHAR(9),
  MODELO       CHAR(3),
  FECHAMONTAJE DATE,
  PRIMARY KEY (NIF_M, MODELO, FECHAMONTAJE),
  FOREIGN KEY (MODELO) REFERENCES MODELODORMITORIO(COD),
  FOREIGN KEY (NIF_M) REFERENCES MONTADOR(NIF)
);

DESCRIBE MONTA;