CREATE DATABASE EJEMPLO2;
USE EJEMPLO2;


CREATE TABLE REGION 
(
  CODREGION INT,
  NOMBRE    VARCHAR(40),
  PRIMARY KEY (CODREGION)
);

DESCRIBE REGION;

CREATE TABLE PROVINCIA
(
  CODPROVINCIA INT,
  NOMBRE       VARCHAR(40),
  CODREGION    INT,
  PRIMARY KEY (CODPROVINCIA),
  FOREIGN KEY (CODREGION) REFERENCES REGION(CODREGION)
);

DESCRIBE PROVINCIA;

CREATE TABLE LOCALIDAD
(
  CODLOCALIDAD INT,
  NOMBRE      VARCHAR(40),
  CODPROVINCIA INT,
  PRIMARY KEY (CODLOCALIDAD),
  FOREIGN KEY (CODPROVINCIA) REFERENCES PROVINCIA(CODPROVINCIA)
);

DESCRIBE LOCALIDAD;

CREATE TABLE EMPLEADO
(
  ID           INT,
  DNI          CHAR(9)   UNIQUE,
  NOMBRE       VARCHAR(50),
  FECHANAC     DATE,
  TELEFONO     CHAR(9),
  SALARIO      FLOAT(6,2),
  CODLOCALIDAD INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (CODLOCALIDAD) REFERENCES LOCALIDAD(CODLOCALIDAD)
);

DESCRIBE EMPLEADO;