CREATE DATABASE Ejemplo1;

USE Ejemplo1;

CREATE TABLE ALUMNO 
(
  NUMMATRICULA    INT auto_increment,
  NOMBRE          VARCHAR(50),
  FECHANACIMIENTO DATE,
  TELEFONO        CHAR(12),
  PRIMARY KEY (NUMMATRICULA)
);

DESCRIBE ALUMNO;

CREATE TABLE PROFESOR 
(
  IDPROFESOR   INT auto_increment,
  NIF_P        CHAR(9) UNIQUE,
  NOMBRE       VARCHAR(50),
  ESPECIALIDAD VARCHAR(50),
  TELEFONO     CHAR(12),
  PRIMARY KEY (IDPROFESOR)
);

DESCRIBE PROFESOR;

CREATE TABLE ASIGNATURA 
(
  CODASIGNATURA  CHAR(6),
  CURSOESCOLAR CHAR(9),
  NOMBRE         VARCHAR(30),
  IDPROFESOR 	INT,
  PRIMARY KEY (CODASIGNATURA, CURSOESCOLAR),
  FOREIGN KEY (IDPROFESOR) REFERENCES PROFESOR(IDPROFESOR)
);

DESCRIBE ASIGNATURA;

CREATE TABLE RECIBE 
(
  NUMMATRICULA  INT,
  CODASIGNATURA CHAR(6),
  CURSOESCOLAR CHAR(9),
  PRIMARY KEY (NUMMATRICULA, CODASIGNATURA),
  FOREIGN KEY (NUMMATRICULA) REFERENCES ALUMNO(NUMMATRICULA),
  FOREIGN KEY (CODASIGNATURA, CURSOESCOLAR) REFERENCES ASIGNATURA(CODASIGNATURA, CURSOESCOLAR)
);

DESCRIBE RECIBE;

